config/routes.rb
Lookshelf::Application.routes.draw do
  get "book/new"
  get "session/new"

  
 get 'auth/:provider/callback', to: 'session#fbcreate'

 get 'auth/failure', to: redirect('/')
 get 'signout', to: 'session#destroy', as: 'signout'  
  
  get "session/new"=>"session#new",:as=>:user_login
  get "session/destroy"=>"session#destroy",:as=>:user_logout

  post "session/create"=>"session#create",:as=>:create_session
  get "user/user_home"=>"user#user_home",:as=>:user_home
   get "user/notification"=>"user#notification",:as=>:user_notification
   post "user/update_notification"=>"user#update_notification",:as=>:update_notification
   
  get "user/user_account"=>"user#user_account",:as=>:user_account
    post "user/update"=>"user#update",:as=>:update_user

  get "user/borrower_page"=>"user#borrower_page",:as=>:borrower_page
  get "user/lander_page"=>"user#lander_page",:as=>:lander_page

  post "user/create_user"=>"user#create_user"  ,:as=>:create_user
  post "user/check_username"=>"user#check_username"
    
  get  "book/new"=>"book#new",:as=>:new_book
  get  "book/add_cate"=>"book#add_cate",:as=>:add_cate
    get  "book/user_book"=>"book#user_book",:as=>:user_book
        get  "book/all_book"=>"book#all_book",:as=>:all_book

  post "book/create"=>"book#create",:as=>:add_book
  post "book/create_cate"=>"book#create_cate",:as=>:create_cate

  post "book/search_book"=>"book#search_book"
    post "book/search_book_by_cate"=>"book#search_book_by_cate"

  
  
  get "book/book_request/:id"=>"book#book_request" ,:as=>:book_request
  get "book/book_response/:id"=>"book#book_response" ,:as=>:book_response
       

  post "book/create_book_request"=>"book#create_book_request" ,:as=>:create_book_request
  post "book/create_book_response"=>"book#create_book_response" ,:as=>:create_book_response

  root 'home#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
 validates_presence_of :title, :tag, :category_id
 has_attached_file :book_image, :styles => { :medium => "300x300>", :thumb => "100x100>", :small => "411x274>", :large => "1280x854>" }, :default_url => "missing.gif"  
  
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  include BookHelper
  protect_from_forgery 
  
  layout "user"
  
  def new
    @book=Book.new
    render :layout=>"user"
  end
  
  def create
    @book=Book.create(book_params)
    if @book.save
    redirect_to user_home_path, :notice=>"Book Added Successfuly"
    else
      render "new" ,:notice=>"Book Not Added"
    end
  end
  
  def search_book
    q=params[:Booktext]
    @book=Book.where('title LIKE ?', "%#{params[:Booktext]}%")
    #puts"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#{@book.inspect}"
     #where('title LIKE ?', "%#{params[:Booktext]}%")
     #where(:title=>params[:Booktext]).all
     #Yogesh:  @user_entity_with_recent = (UserEntity.,:is_active => "true").in(:user_category_id => @cate).order_by(:created_at => "desc")| UserEntity.where(:is_active => "true",:sub_category => Regexp.new(("."+q+"."), Regexp::IGNORECASE)).in(:user_category_id => @cate).order_by(:created_at => "desc") ).group_by { |t| t.api_id }
   respond_to do |format|
       format.json {render :json=>@book}
       puts"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#{@book.inspect}"
   end
   
 end
   
   
   def search_book_by_cate
     @book=Book.where(:category_id=>params[:Cid])
       respond_to do |format|
       format.json {render :json=>@book}
       
     end
   end
   
   
   def user_book
   @book=Book.where(:user_id=>session[:user_id])  
   end
   
   def all_book
   @book=Book.all 
   @cate=Category.all
   end
  
  
  def book_request
    
    if session[:user_id]
      @book=Book.where(:id=>params[:id]).first 
    
      #@book_lander=User.where(:id=>params[:Book_lander_id]).first
    
      render "book_request", :layout => "layouts/user"
 
    else
      
      redirect_to root_url ,:notice=>"Please login first.........."
                    
    end
    
  end
  
  def book_response
    @bookreq=BookRequest.where(:id=>params[:id]).first
    @bookres=BookResponse.new
    #@book_lander=User.where(:id=>params[:Book_lander_id]).first
    
    render "book_response" , :layout => "layouts/user"
      
  end

   def create_book_response
    @bookres=BookResponse.new
    @bookres.book_request_id=params[:book_response][:request_id]
    @bookres.return_date=params[:book_response][:return_date]
    @bookres.status="Delivered"
    @bookres.save
    
    if @bookres.save
    @reqbookstatus=BookRequest.where(:id=>params[:book_response][:request_id]).first
    @book=Book.where(:id=> @reqbookstatus.book_id).first
    @book.update_attributes(:status => "loaned Out")
    @reqbookstatus.update_attributes(:status => "Delivered")  
     
    redirect_to lander_page_path ,:notice=>"Request Proceed Successfully"
     
    else
       render :action=>"book_response"
    end
       
    
  end
   def add_cate
    
   @cate=Category.new 
   end
   
   def create_cate
     @cate=Category.create(cate_params)
    if @cate.save
    redirect_to add_cate_path ,:notice=>"Category Added Successfully"
    else
      redirect_to add_cate_path ,:notice=>"There was a problem" 
   end
   end 
   
   def cate_params
     params.require(:cate).permit(:name,:description)
   end
     
  
   def create_book_request
      
    @book_lander_id=Book.where(:id=>params[:book_request][:book_id]).first
   
    @bookreq=BookRequest.new
    @bookreq.book_id=params[:book_request][:book_id]
    @bookreq.lander_book_id=@book_lander_id.user_id
    @bookreq.user_id=session[:user_id]
    @bookreq.status="Waiting"
    @bookreq.date_of_request= Time.now
    @bookreq.save!
   
    if @bookreq.save
      @notification=Notification.new
      @notification.update_attributes(:not_by=>session[:user_id],:not_msg=>"One user want to borrow your book",:not_to=>@book_lander_id.user_id,:status=>"unread",:is_active=>"1")
    if @notification.save
      redirect_to user_home_path, :notice=>"Book Request Successfuly"
    else
      render user_home_path, :notice=>"Book Request Not Send"
    end
    
    end
             
   end
  
  

  def book_params
    params.require(:book).permit(:title,:tag,:description,:category_id,:user_id,:status,:book_image)
  end
  
end

app/helpers/book_helper.rb
module BookHelper
   def getBookDetail(id)
    @book=Book.where(:id=>id).first
    return @book
  end
  
  def getUserDetail(id)
    @user=User.where(:id=>id).first
    return @user
  end
end

app/views/book/add_cate.html.erb
<div>
<% if @cate.errors.any? %>
<div class="error_messages">
<h2>Form is invalid</h2>
<ul>
<% for message in @cate.errors.full_messages %>
<li><%= message %></li>
<% end %>
</ul>
</div>
<%end%>

<%=form_for @cate ,:as=>:cate,:method=>"post",:url=>create_cate_path do |f| %>
	<table id="customers">
		<tr>
			<th colspan="2">Add Category</th>
		</tr>
			
		<tr>
			<td>Category Name</td>
			<td><div class="input_div">
		<%=f.text_field :name ,:class=>"input"%>
	</div></td>
		</tr>
			<tr>
			<td> Description</td>
			<td><div class="input_div">
		<%=f.text_area :description %>
	</div></td>
		</tr>
			<tr>
						
			<td colspan="2" align="center"><div class="div_book_status">
				<%=f.submit "submit", :class=>"submit" %>
			</div>
			</td>
			</tr>
			</table>
			<%end%>
</div>

app/views/book/all_book.html.erb
<br />
<div id="sort_by_category">
	Category<%= select("categry","category_id",@cate.collect{|c| [c.name,c.id] },{prompt:'Select Category'})%>
    &nbsp;&nbsp;<%=link_to "All Book",all_book_path%>
</div>
<br />
<div id="all_book">
<table id="all_book_table" class="customers">
	<tr>
		<th>Book Title </th>
		<th>Detail</th>
		<th>Send Request</th>
    </tr>
    <%if @book.present?%>
    <%@book.each do |b|%>
    <tr>
    	<td><%=b.title%></td>
    	<td><%=b.status%></td>
    	<td><%=link_to "SendRequest",book_request_path(b.id)%></td>
    <%end%>
    <%end%>
</table>

</div>

app/views/book/book_request.html.erb
<div id="divimagebox" style="display: none; margin-left: 900px;position: absolute; margin-top:10px;background-color: #fff;
border-width: 1px 3px 3px 1px;
border-style: solid;
border-color: #c0c0c0;
padding: 8px 0px 6px 6px;
position: absolute;
text-align: left;
width: 230px;
min-height: auto;
align:right;
float: right">
 <img id="book_image" src="" />
</div>

<div >
	<%=form_for @book ,:as=>:book_request,:method=>"post",:url=>create_book_request_path do |f| %>
	<table id="customers">
		<tr>
			<th colspan="2">Book Detail</th>
		</tr>
			
		<tr>
			<td>Book Title</td>
			<td><div class="input_div">
				<%=@book.title%>
		<%=f.hidden_field :book_id ,:value=>@book.id%>
	</div></td>
		</tr>
			<tr>
			<td>Book Description</td>
			<td><div class="input_div">
		<%=@book.description%>
	</div></td>
		</tr>
			<tr>
			<td>Book Status</td>
			<td><div class="div_book_status">
				<%=@book.status%>

	</div></td>
		</tr>
		<tr>
			<td>Book Image</td>
			<td><div class="input_div">
				
			<a href="#" ><%= image_tag @book.book_image(:thumb) ,:size=>"50x50" ,:class=>"book_images" %></a>	

				

	</div></td>
		</tr>
			<tr>
			<td>Book Lender</td>
			<td><div class="input_div">
				<%@user=getUserDetail(@book.user_id)%>
		       <%=@user.name%>
	</div></td>
		</tr>
			<tr>
			<td>Book Lender Address</td>
			<td><div class="input_div">
					 <%=@user.shipping_address%>
	</div> </td>
		</tr>
		</tr>
			<tr>
			<td></td>
			<td><div class="input_div">
			
		<%=f.submit 'SubmitRequest'%>
		
	</div></td>
		</tr>
	</table>
	
	<%end%>
	
	
	
</div>

<script type="text/javascript">

$(document).ready(function(){
 		
 				$(".book_images").mouseenter(function(){

 		
 			  		var src = $(this).attr('src');
 			  		 $("#book_image").attr('src', $(this).attr('src').replace('/thumb', '/large'));
 			  		$('#divimagebox').show();
 			
 				});
 				
 		       $(".book_images").mouseleave(function(){
   					 $('#divimagebox').hide();
				});
				
				 var book_status=String($('.div_book_status').html());
			    var str=$.trim(book_status);
				if(str=="loaned Out"){
					
				
						$('.div_book_status').closest("tr").css("color","red");
										

				}
				else
				{
					$('.div_book_status').closest("tr").css("color","green");
				}


});
</script>

app/views/book/book_response.html.erb
<div >

	<%=form_for @bookres ,:as=>:book_response,:method=>"post",:url=>create_book_response_path do |f| %>
	<table id="customers">
		<%if @bookreq.present? %>
		<tr>
			<td>Book Title</td>
			<td><div class="input_div">
				
				<%@book=getBookDetail(@bookreq.book_id) %>
				<%=@book.title %>
		<%=f.hidden_field :request_id ,:value=>@bookreq.id%>
	</div></td>
		</tr>
			<tr>
			<td>Book Description</td>
			<td><div class="input_div">
				
		<%=@book.description %>
	</div></td>
		</tr>
			<tr>
			<td>Book Status</td>
			<td><div class="input_div">
		<%=@book.status %>

	</div></td>
		</tr>
		<tr>
			<td>Book Request Date</td>
			<td><div class="input_div">
				<%=@bookreq.date_of_request%>
				
	</div></td>
		</tr>
			<tr>
			<td>Book Borrower</td>
			<td><div class="input_div">
				<% @user=getUserDetail(@bookreq.user_id)%>
				<%=@user.name%>
						
	</div></td>
		</tr>
			<tr>
			<td>Book Borrower Address</td>
			<td><div class="input_div">
				<%=@user.shipping_address %>
	</div> </td>
		</tr>
		<%end%>
			
			<tr>
			<td>Book Return Date</td>
			<td><div class="input_div">
				<%=f.text_field :return_date ,:id=>"datepicker" %>
	</div></td>
		</tr>
		
			<tr>
		
			<td colspan="2" style="text-align: center"><div class="input_div">
			
		<%=f.submit 'SubmitRequest'%>
	</div></td>
		</tr>
	</table>
	
	<%end%>
	<div style="float: left;margin-left: 300px;"><%=link_to "Go Back", lander_page_path %></div>
		
	
</div>

app/views/book/new.html.erb
<% if @book.errors.any? %>
<div class="error_messages">
<h2>Form is invalid</h2>
<ul>
<% for message in @book.errors.full_messages %>
<li><%= message %></li>
<% end %>
</ul>
</div>
<%end %>
<%= form_for@book,:as=>:book ,:method=>"post" ,:url=>add_book_path do |f| %>
							
						
						<table style="margin-top: 15px;"> 
							<tr>
								<th style="text-align: left;">Add Book</th>
							</tr>
								<tr>
				<td><%=f.label :Category%>
									<div class="input_div">

	<%=f.select(:category_id,Category.all.collect{|c| [c.name,c.id] },{prompt:'Select Category'}, :onchange => "collectionSelected(this);")%>
				</div>
			</td>
			</tr>
							
			<tr>
				<td>Book Title
					<div class="input_div">
						<%=f.text_field :title ,:placeholder=>"Some text" ,:class=>"input"%>
							<%=f.hidden_field :user_id ,:value=>session[:user_id] %>
					</div>
					
				</td>
				
			</tr>
			<tr>
				<td>BooK Tag
					<div class="input_div">
						<%=f.text_field :tag, :class=>"user_name" ,:class=>"input" %>
						<div class="check"></div>
					</div>
					
				</td>
				
		</tr>
			
			<tr>
				<td>Description
					<div class="input_div">
						<%= f.text_area :description%>
						<%=f.hidden_field :status ,:value=>"Available" %>
					</div>
					
				</td>
				
			</tr>
			<tr>
				<td>Image
					<div class="input_div">
						<%= f.file_field :book_image%>
					</div>
					
				</td>
				
			</tr>
			
			<tr>
				<td>
				<%=f.submit "submit", :class=>"submit" %>
				</td>
				
			</tr>
			
			</table>
	
					
						<%end%>

app/views/book/user_book.html.erb
<table id="customers">
		<tr>
		<th colspan="5">Books You Want</th>
	</tr>
	<tr>
		<th>
			No.
		</th>
		<th>
			BookTitle
		</th>
		<th>
			Tag
		</th>
		<th>
			Description
		</th>
		<th>
			Status
		</th>
			</tr>
	<%@no=0%>
	
	<%@book.each do |r| %>
	<tr>
		<td>
			<%=@no=@no+1%>
		</td>
		<td>
								<%=r.title%>
	
		</td>
		<td>
			<%=r.tag%>
		</td>
		
		<td>
			<%=r.description%>
			
		</td>
		
		<td>
			<%=r.status%>
			
		</td>
		
	</tr>
<%end%>
</table>