config/routes.rb
Lookshelf::Application.routes.draw do
  get "book/new"
  get "session/new"

  
 get 'auth/:provider/callback', to: 'session#fbcreate'

 get 'auth/failure', to: redirect('/')
 get 'signout', to: 'session#destroy', as: 'signout'  
  
  get "session/new"=>"session#new",:as=>:user_login
  get "session/destroy"=>"session#destroy",:as=>:user_logout

  post "session/create"=>"session#create",:as=>:create_session
  get "user/user_home"=>"user#user_home",:as=>:user_home
   get "user/notification"=>"user#notification",:as=>:user_notification
   post "user/update_notification"=>"user#update_notification",:as=>:update_notification
   
  get "user/user_account"=>"user#user_account",:as=>:user_account
    post "user/update"=>"user#update",:as=>:update_user

  get "user/borrower_page"=>"user#borrower_page",:as=>:borrower_page
  get "user/lander_page"=>"user#lander_page",:as=>:lander_page

  post "user/create_user"=>"user#create_user"  ,:as=>:create_user
  post "user/check_username"=>"user#check_username"
    
  get  "book/new"=>"book#new",:as=>:new_book
  get  "book/add_cate"=>"book#add_cate",:as=>:add_cate
    get  "book/user_book"=>"book#user_book",:as=>:user_book
        get  "book/all_book"=>"book#all_book",:as=>:all_book

  post "book/create"=>"book#create",:as=>:add_book
  post "book/create_cate"=>"book#create_cate",:as=>:create_cate

  post "book/search_book"=>"book#search_book"
    post "book/search_book_by_cate"=>"book#search_book_by_cate"

  
  
  get "book/book_request/:id"=>"book#book_request" ,:as=>:book_request
  get "book/book_response/:id"=>"book#book_response" ,:as=>:book_response
       

  post "book/create_book_request"=>"book#create_book_request" ,:as=>:create_book_request
  post "book/create_book_response"=>"book#create_book_response" ,:as=>:create_book_response

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user=User.new
  end
  
   # if params[:entity_image]
   #           post_image = (params[:entity_image]).gsub(" ", "+")
   #          @entity_image = StringIO.new(Base64.decode64(post_image))
   #         @entity_image.class.class_eval { attr_accessor :original_filename, :content_type }
   #        @entity_image.original_filename = "entity_image.png"
   #       @entity_image.content_type = "image/png"
   # end
  

  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div id="login_window" style="display: block;
position: absolute;
opacity: 1;
z-index: 11000;
left: 50%;
margin-left: -238px;
top: 20px;width: 20%;
text-align: center;">
<a class="close_window" href="#">x</a>
	<%= form_tag create_session_path ,:id=>"loginform" do %>

<%= label_tag :email %><br />
<%= text_field_tag :email, params[:email] ,:class=>"input" %><br />

<%= label_tag :password %><br />
<%= password_field_tag :password , '',:class=>"input"  %>

<p class="button"><%= submit_tag 'Login' ,:class=>"submit"%></p>
<% end %>
<%= link_to "Forgot Password" ,"#" ,:id=>"mylink"%>
	
	</div>



<div id="mani" style="margin-left: 100px;">
	
	<box>
		<table>
		<tr>
				<td>
				<div id="how_to_use">
		<h2>How to use Look Shelf</h2>
		<video width="320" height="240" controls autoplay>
  <source src="movie.ogg" type="video/ogg">
  <source src="movie.mp4" type="video/mp4">
  <object data="movie.mp4" width="320" height="240">
    <embed width="320" height="240" src="movie.swf">
  </object>
</video>
		
	</div>
				</td>
				<td>
				<% if @user.errors.any? %>
			<div  class="error_messages">
				<h2>Form is invalid</h2>
				<ul>
				<% for message in @user.errors.full_messages %>
				<li><%= message %></li>
				<% end %>
				</ul>
			</div>
				<% end %>
				 <div id="sign_up_window" style="align:right;margin-left: 50px;">
						<%= form_for@user,:as=>:user ,:method=>"post" ,:url=>create_user_path,:id=>"registrationForm" do |f| %>
							
						<div id="sign_up_window1">
						<table> 
							
			<tr>
				<td>Your Name
					<div class="input_div">
						<%=f.text_field :name ,:placeholder=>"Some text" ,:class=>"input",:autocomplete=>"off"%>
					</div>
					
				</td>
				
			</tr>
			<tr>
				<td>User Name
					<div class="input_div">
						<%=f.text_field :username , :class=>"user_name" ,:class=>"input",:autocomplete=>"off" %>
						<div class="check"></div>
					</div>
					
				</td>
				
		</tr>
			
			<tr>
				<td>Your Email
					<div class="input_div">
						<%= f.text_field :email ,:class=>"input", :autocomplete=>"off"%>
					</div>
					
				</td>
				
			</tr>
			<tr>
				<td>Password
					<div class="input_div">
						<%= f.password_field :password ,:class=>"input" %>
					</div>
					
				</td>
				
			</tr>
			 
			<tr>
				<td>
				<input type="button" value="submit" id="btnNext" class="submit" />	
				</td>
				
			</tr>
			
			</table>
	
						</div>
						<div id="sign_up_window2">
							<h3>Step 2</h3>
						<table> 
			<tr>
				<td>Your Address
					<div class="input_div">
						<%=f.text_field :shipping_address ,:class=>"input"%>
					</div>
					
				</td>
				
			</tr>
			<tr>
				<td>Zip Code
					<div class="input_div">
						<%=f.text_field :zip_code ,:class=>"input" %>
					</div>
					
				</td>
				
		</tr>
			
			<tr>
				<td>City
					<div class="input_div">
						<%= f.text_field :city ,:class=>"input"%>
					</div>
					
				</td>
				
			</tr>
			<tr>
				<td>Phone
					<div class="input_div">
						<%= f.text_field :phone ,:class=>"input"%>
					</div>
					
				</td>
				
			</tr>
			<tr>
				<td>Photo
					<div class="input_div">
						<%= f.file_field :photo ,:class=>"input" ,:onchange=>'Test.UpdatePreview(this)' %>
					</div>
					
				</td>
				
			</tr>
			<tr>
				<td>
					<div class="borderDiv">
		    			<div style="position:relative;width:300px;height:250px" id="cropImage"><img src="" id="preveiwphoto" height="250" width="300"/></div>
	     </div>
					 
					 <%= f.hidden_field :width, :value=>"" %>
					 <%= f.hidden_field :height, :value=>"" %>
					 <%= f.hidden_field :marginleft, :value=>"" %>
					 <%= f.hidden_field :marginright, :value=>"" %>

					
				</td>
				
			</tr>
			<tr>
				<td>
					Preview
		<div class="frame" style="margin: 0 1em; width: 100px; height: 100px; margin-bottom: 30px;">
      	 
      	 <div id="preview" style="width:100px;height:100px; overflow:hidden;">
        	<img src="" style="width: 100px; height: 100px;" id="preveiwpt">
      	 </div>
      	 
    	</div>
				</td>
			</tr>
			
			<tr>
				<td>
				<input type="submit" value="submit" class="submit" />	
				</td>
				
			</tr>
			
			</table>
	
						</div>
							

						<%end%>
		
		
		
	</div>
				</td>
			</tr>
		</table>
		
	
	
	</box>
</div>


<script type="text/javascript">
	
	jQuery(document).ready(function($){
				
		var checkUsername;
		var  validator = $("#new_user").validate( {

        rules:{
        	 "user[name]": "required",
        	 "user[username]":"required",
        	  "user[phone]": "required",
            "user[password]": {
      		required: true,
    	  minlength: 6
	    },
            "user[email]": "required email"
        },
        messages:{
            "user[name]": "Name Required",
             	 "user[username]":"User Name Required",
            "user[phone]": "Phone Number Required",
             "user[password]": {
                required: "Enter Password",
                minlength: "Enter Minimum 6 character"
              },
           "user[email]": {
                required: "Enter email",
                email: "Enter valid email"
            	}
        	}
        	
    	});
    	
    	$('#new_user').blur(function(){
		    validator.validate();
		});
		
		$('#sign_up_window2').hide();
		$('#btnNext').click( function(){
			if($('#new_user').valid() && checkUsername ){
				$('#sign_up_window2').show();
				$('#sign_up_window1').hide(); $("#login_window").hide();
			}else{
				
			}
			
		});
		
		   $('.close-green').click(function(){
  	
  	        $('#message-green').hide();
  	
           });
		
	
	
	
	$(function()
 {
  $('#user_username').keyup(function()
  {
  var checkname=$(this).val();
  

  if(checkname!=''){
  $('.check').show();


 var uname = checkname;
  $.ajax({

          type: "POST",         
          data: {Uname:uname},
           url: "/user/check_username",
          dataType: "JSON",
         
          success: function(result){

                         
                           
               if(result){
					  $('.check').html('This Username Is Already Taken');

                      $(".check").css("color","red");
                      
                    
                      $('.check').addClass("red");
                      $(".user_name").removeClass("white");
                      $(".user_name").addClass("yellow");
						
                

               }else{

                       $('.check').html('This Username Is Avaliable');
						
						checkUsername=true;
                       $(".check").css("color","green");
                    
                       $(".user_name").removeClass("yellow");
                       $(".user_name").addClass("white");
            }
         }

      });

   }else{

       $('.check').html('');

       }

  });
  
 });
 
  $("input").on("keydown", function (e) {
       return e.which !== 32;
  });
    
	
   

});



</script>