config/routes.rb
Lookshelf::Application.routes.draw do
  get "book/new"
  get "session/new"

  
 get 'auth/:provider/callback', to: 'session#fbcreate'

 get 'auth/failure', to: redirect('/')
 get 'signout', to: 'session#destroy', as: 'signout'  
  
  get "session/new"=>"session#new",:as=>:user_login
  get "session/destroy"=>"session#destroy",:as=>:user_logout

  post "session/create"=>"session#create",:as=>:create_session
  get "user/user_home"=>"user#user_home",:as=>:user_home
   get "user/notification"=>"user#notification",:as=>:user_notification
   post "user/update_notification"=>"user#update_notification",:as=>:update_notification
   
  get "user/user_account"=>"user#user_account",:as=>:user_account
    post "user/update"=>"user#update",:as=>:update_user

  get "user/borrower_page"=>"user#borrower_page",:as=>:borrower_page
  get "user/lander_page"=>"user#lander_page",:as=>:lander_page

  post "user/create_user"=>"user#create_user"  ,:as=>:create_user
  post "user/check_username"=>"user#check_username"
    
  get  "book/new"=>"book#new",:as=>:new_book
  get  "book/add_cate"=>"book#add_cate",:as=>:add_cate
    get  "book/user_book"=>"book#user_book",:as=>:user_book
        get  "book/all_book"=>"book#all_book",:as=>:all_book

  post "book/create"=>"book#create",:as=>:add_book
  post "book/create_cate"=>"book#create_cate",:as=>:create_cate

  post "book/search_book"=>"book#search_book"
    post "book/search_book_by_cate"=>"book#search_book_by_cate"

  
  
  get "book/book_request/:id"=>"book#book_request" ,:as=>:book_request
  get "book/book_response/:id"=>"book#book_response" ,:as=>:book_response
       

  post "book/create_book_request"=>"book#create_book_request" ,:as=>:create_book_request
  post "book/create_book_response"=>"book#create_book_response" ,:as=>:create_book_response

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name,:username,:email,:password
  validates_uniqueness_of :username,:email
  attr_accessor :password
has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>", :small => "411x274>", :large => "1280x854>" }, :default_url => "missing.gif"  
 before_save :encrypt_password

 def encrypt_password
 if password.present?
 self.password_salt = BCrypt::Engine.generate_salt
 self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
 end
 end
 
 def self.authenticate(email, password)
user = find_by_email(email)
if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
user
else
nil
end
end



end

app/controllers/user_controller.rb
class UserController < ApplicationController
  include BookHelper
  include UserHelper
  protect_from_forgery 
  
  def create_user
    
  @user=User.create(user_params)
  if @user.save
   redirect_to root_url ,:notice=>"Registred Successfuly Please do login"
  else
    render "home/index" ,:notice=>"There was a problem"
   
  end
  end
  
  def check_username
    @user=User.where(:username=>params[:Uname]).first
    
      respond_to do |format|
    if @user.present?
        format.json {render :json=>@user}
   else 
     @status="false"
     format.json {render :json=>@status}
    end
   end
    
  end
  
  def user_home
    if session[:user_id]
    @user=User.where(:id=>session[:user_id]).first
    else
    redirect_to root_url ,:notice=>"Please do login first"
    end
  end
  
  def notification
     @notification=Notification.where(:status=>"unread",:not_to=>session[:user_id])
    
      respond_to do |format|
    if @notification.present?
        format.json {render :json=>@notification}
   else 
     @status="false"
     format.json {render :json=>@status}
    end
   end
    
  end
  
  
  def update_notification
  @notification =Notification.where(:id=>params[:Nid]).first
  @notification.update_attributes(:status => "read")
  
   #@notification.update_attribute(:status, "read")
    respond_to do |format|
      if @notification.save
   
     format {render :json=>@notification }
      end
   end  
  end
  
  def borrower_page
    @arrdays=[]
    @arrreturndate=[]
    @bookreq=BookRequest.where(:user_id=>session[:user_id])
    
    @bookreq.each do |r|
    @bookres=BookResponse.where(:book_request_id=>r.id).first
    if @bookres.present?
    @daysleft=DateTime.parse(@bookres.return_date.to_s).mjd-DateTime.now.mjd 
    @arrreturndate<<@bookres.return_date
    @arrdays<<@daysleft.to_i
    end
    
    end
    
    
      
  end
  
  def lander_page
    @arrdays=[]
    @arrreturndate=[]
    @bookreq=BookRequest.where(:lander_book_id=>session[:user_id])
     if @bookreq.present?
    @bookreq.each do |r|
    @bookres=BookResponse.where(:book_request_id=>r.id).first
    if @bookres.present?
    @daysleft=DateTime.parse(@bookres.return_date.to_s).mjd-DateTime.now.mjd 
    @arrreturndate<<@bookres.return_date
    @arrdays<<@daysleft.to_i  
    end
    
    end
    end
     
  end
  
  def user_account
    @user=User.where(:id=>session[:user_id]).first  
  end
  
  def update
    @user=User.where(:id=>session[:user_id]).first
    @user.update_attributes(user_params)
    
    if @user.save
    render "user_account" , :notice=>"User Updated Successfuly"
    else 
    render :user_account , :notice=>"There was a Successfuly"
      
      
    end
    
    
  end 
  
  private
  def user_params
    params.require(:user).permit(:name,:username,:email,:password,:shipping_address,:phone,:city,:zip_code,:photo,:width,:height,:marginleft,:marginright)
  end
  
end

app/helpers/user_helper.rb
module UserHelper
  
  def getUserDetail(id)
    @user=User.where(:id=>id).first
    return @user
  end
  
  def getNotification
    @notification=Notification.where(:status=>"unread",:not_to=>session[:user_id])
    return @notification
  end
  
end

app/views/user/borrower_page.html.erb
<table id="customers">
		<tr>
		<th colspan="5">Books You Want</th>
	</tr>
	<tr>
		<th>
			No.
		</th>
		<th>
			BookTitle
		</th>
		<th>
			Status
		</th>
		<th>
			Return Date
		</th>
		<th>
			
			Days Left
			</th>
	</tr>
	<%@no=0%>
	<%@el=0%>
	<%@rd=0%>
	<%if @bookreq.present?%>
	<%@bookreq.each do |r| %>
	<tr>
		<td>
			<%=@no=@no+1%>
		</td>
		<td>
					<%@book=getBookDetail(r.book_id)%>
					<%=@book.title%>
	
		</td>
		<td>
			<%=r.status%>
		</td>
		
		<td>
			<%=@arrreturndate[@rd]%>
			
		</td>
		
		<td class="daysleft">
			
			
			<%if @arrdays[@el]!=nil %>
			<% if (@arrdays[@el]) > 0%>
			<%=@arrdays[@el] %>
			
			<%else %>

				Over due <%=@arrdays[@el].to_s.at(1..2) %> days
			<%end%>
			<%end%>
				
		</td>
		<%@el=@el+1%>
		<%@rd=@rd+1%>
	</tr>
<%end%>
<%end%>
</table>

app/views/user/lander_page.html.erb
<table id="customers">
	<tr>
		<th colspan="7"> Request For Your Book</th>
	</tr>
	<tr>
		<th>
			No.
		</th>
		<th>
			BookTitle
		</th>
		<th>
			Date of Request
		</th>
		<th>
			Status
		</th>
		<th>
			Return Date
		</th>
		<th>
			
			Days Left
			</th>
		<th>
			Action
		</th>
	</tr>
	<%@no=0%>
	<%@el=0%>
	<%if @bookreq.present?%>
	<%@bookreq.each do |r| %>
	<tr>
		<td>
			<%=@no=@no+1%>
		</td>
		<td>
		
			<%@book=getBookDetail(r.book_id)%>
					<%=@book.title%>
		</td>
		<td>
			<%=r.date_of_request.to_date.strftime("%Y/%m/%d") %>
		</td>
		<td>
			<%=r.status%>
		</td>
		
		<td>
			<%=@arrreturndate[@el]%>
			
		</td>
		<td class="daysleft">
			
		
			<%if @arrdays[@el]!=nil %>
			<%if @arrdays[@el]>0 %>
			<%=@arrdays[@el]%>
			<%else %>
			Over due	<%=@arrdays[@el].to_s.at(1..2) %> days
			<%end%>
			<%end%>
		
			
		</td>
		<%@el=@el+1%>
		<td>
			<%=link_to "Response", book_response_path(r.id) %>/<%=link_to "Detail", book_response_path(r.id)%>
		</td>
	</tr>
<%end%>
<%end%>
</table>

app/views/user/user_account.html.erb
<% if @user.errors.any? %>
<div class="error_messages">
<h2>Form is invalid</h2>
<ul>
<% for message in @user.errors.full_messages %>
<li><%= message %></li>
<% end %>
</ul>
</div>
<% end %>

		<div id="sign_up_window" style="margin-top: 20px;">
						<%= form_for@user,:as=>:user ,:method=>"post" ,:url=>update_user_path,:id=>"registrationForm" do |f| %>
							
						<div id="sign_up_window1">
						<table> 
							
			<tr>
				<td>Your Name
					<div class="input_div">
						<%=f.text_field :name ,:placeholder=>"Some text", :class=>"input"%>
					</div>
					
				</td>
				
			</tr>
			<tr>
				<td>User Name
					<div class="input_div">
						<%=f.text_field :username , :class=>"user_name" , :class=>"input" %>
						<div class="check"></div>
					</div>
					
				</td>
				
		</tr>
			
			<tr>
				<td>Your Email
					<div class="input_div">
						<%= f.text_field :email ,:value=>@user.email , :class=>"input"%>
					</div>
					
				</td>
				
			</tr>
			<tr>
				<td>Password
					<div class="input_div">
						<%= f.password_field :password , :class=>"input" %>
					</div>
					
				</td>
				
			</tr>
			
			
			<tr>
				<td>Your Address
					<div class="input_div">
						<%=f.text_field :shipping_address ,:value=>@user.shipping_address , :class=>"input"%>
					</div>
					
				</td>
				
			</tr>
			<tr>
				<td>Zip Code
					<div class="input_div">
						<%=f.text_field :zip_code ,:value=>@user.zip_code , :class=>"input"%>
					</div>
					
				</td>
				
		</tr>
			
			<tr>
				<td>City
					<div class="input_div">
						<%= f.text_field :city ,:value=>@user.city , :class=>"input" %>
					</div>
					
				</td>
				
			</tr>
			<tr>
				<td>Phone
					<div class="input_div">
						<%= f.text_field :phone ,:value=>@user.phone , :class=>"input"%>
					</div>
					
				</td>
				
			</tr>
			<tr>
				<td>
						<div class="frame" style="margin: 0 1em; width: 100px; height: 100px;">
      	 
      	 	<div id="preview" style="width:100px;height:100px; overflow:hidden;">
      	 		            <script>
      	 		            	
      	 		            	$('#preview img').css({
        width: <%=@user.width%>,
        height: <%=@user.height%>,
        marginLeft:<%=@user.marginleft%>,
        marginTop: <%=@user.marginright%>
    });
      	 		            </script>
    			<%= image_tag @user.photo.url(:large) ,:id=>"photo"%>
 			</div>
      	 
    	</div>
				</td>
			</tr>
			
			<tr>
				<td>
				<input type="submit" value="update" class="submit" />	
				</td>
				
			</tr>
			
			</table>
	
						</div>
							

						<%end%>
		
		
		
	</div>
	<script type="text/javascript">
	
	$(document).ready(function(){

		var  validator = $("#new_user").validate( {

        rules:{
        	 "user[name]": "required",
        	  "user[phone]": "required",
            "user[password]": {
      	required: true,
      minlength: 6
    },
            "user[email]": "required email"
        },
        messages:{
            "user[name]": "Required",
            "user[phone]": "Required",
             "user[password]": {
                required: "Enter Password",
                minlength: "Enter Minimum 6 character"
              },
           "user[email]": {
                required: "Enter email",
                email: "Enter valid email"
            	}
        	}
    	});
    	
    	$('#new_user').blur(function(){
		    validator.validate();
		 
		});
		
		$('#sign_up_window2').hide();
		$('#btnNext').click( function(){
			if($('#new_user').valid()){
				$('#sign_up_window2').show();
				$('#sign_up_window1').hide(); 
			}else{
				
			}
			
		});
		
	})
	
	
	$(function()
 {
  $('#user_username').keyup(function()
  {
  var checkname=$(this).val();
  

  if(checkname!=''){
  $('.check').show();


 var uname = checkname;
  $.ajax({

          type: "POST",         
          data: {Uname:uname},
           url: "/user/check_username",
          dataType: "JSON",
         
          success: function(result){

                         
                           
               if(result){
					  $('.check').html('This Username Is Already Taken');

                      $(".check").css("color","red");
                    
                      $('.check').addClass("red");
                      $(".user_name").removeClass("white");
                      $(".user_name").addClass("yellow");
						
                

               }else{

                       $('.check').html('This Username Is Avaliable');

                       $(".check").css("color","green");
                    
                       $(".user_name").removeClass("yellow");
                       $(".user_name").addClass("white");
            }
         }

      });

   }else{

       $('.check').html('');

       }

  });

});



	
	
	
	
	
	
</script>

app/views/user/user_home.html.erb
  <div class="FBG">
    <div class="FBG_resize">
      <div class="blok">
        <h2><span>Book</span> Gallery</h2>
        <img src="/images/gallery_1.gif" alt="" width="68" height="68" /><img src="/images/gallery_2.gif" alt="" width="68" height="68" /><img src="/images/gallery_3.gif" alt="" width="68" height="68" /><img src="/images/gallery_4.gif" alt="" width="68" height="68" /><img src="/images/gallery_5.gif" alt="" width="68" height="68" /><img src="/images/gallery_6.gif" alt="" width="68" height="68" />
        <div class="clr"></div>
        <h2>Contact Info </h2>
        <p><strong>Phone</strong>: +1234567<br />
          <strong>Address</strong>: 123 Put Your Address Here <br />
          <strong>E-mail:</strong> me@jungleland.com<br />
          <a href="#">contact page</a></p>
      </div>
      <div class="blok">
        <h2><span>Lorem</span> Ipsum</h2>
        <p>Lorem ipsum dolor Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu posuere nunc justo tempus leo. <br />
          Donec mattis, purus nec placerat bibendum, dui pede condimentum odio, ac blandit ante orci ut diam.</p>
        <ul>
          <li><a href="#">• consequat molestie</a></li>
          <li><a href="#">• sem justo</a></li>
          <li><a href="#">• semper</a></li>
          <li><a href="#">• magna sed purus</a></li>
        </ul>
      </div>
      <div class="blok">
        <h2>Lorem Ipsum</h2>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu posuere nunc justo tempus leo. llorem, eu posuere nunc justo tempus leo. Donec mattis, purus nec placerat bibendum, dui pede condimentum odio, ac blandit ante orci ut diam.</p>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. Cras id urna. <a href="#">Learn more...</a></p>
        <p><br />
        </p>
      </div>
      <div class="clr"></div>
    </div>
  </div>